### ISSUE TITLE
Install problem on Chrome Extension Store

### ISSUE THREAD

**Issue by vibetribe** [Wouter0100/Spell-Check-Language-Changer#1]
https://www.dropbox.com/s/2dychcoppxx2u59/Screenshot%202014-12-05%2021.16.12.png?dl=0

Windows 7 x64. Any idea how I can fix that?

**Comment by Wouter0100** [comment]
Did you enable "Extensions on chrome:// URLs" from this (chrome://flags/) page? This is unfortunately required since we're using a workaround to change the current language which isn't available in Chrome's API's.

**Comment by vibetribe** [comment]
Thank you, this worked.

**Comment by grofte** [comment]
Ahhhh... I didn't understand the explanation in the Chrome Store. 
Go to "chrome://flags" in the address bar. 
Click "Enable" on "Extensions on chrome:// URLs"
Restart Chrome - or reboot computer.

Works now. Awesome, thank you.

**Comment by Wouter0100** [comment]
Exactly, great you got it working! If you've any further feedback, don't hesitate to open a issue :-)
