### ISSUE TITLE
doesn't work?

### ISSUE THREAD

**Issue by 304NotModified** [Wouter0100/Spell-Check-Language-Changer#2]
Nice extension, I got it installed after checking #1 

But it doesn't work? I'm doing something wrong? Is Chrome 46 supported? 

![image](https://cloud.githubusercontent.com/assets/5808377/11032972/fd53d40a-86df-11e5-9aab-7e114a17e78a.png)

**Comment by Wouter0100** [comment]
I'm having issues to myself. I'll get into this soon.

**Comment by Wouter0100** [comment]
Hmm, not sure why Chrome doesn't update the language anymore. 

``` js
chrome.send('setStringPref', ["spellcheck.dictionaries", "nl"]);
chrome.send('spellCheckLanguageChange', [ 'nl' ]);
chrome.send('coreOptionsUserMetricsAction', ['Options_Languages_SpellCheck']);
```

Doesn't seems to work..

**Comment by 304NotModified** [comment]
thanks for the confirmation!

So normally all the 3 options should work? Or 1 of them?

**Comment by Wouter0100** [comment]
These 3 commands needs to be executed in order to properly change the language, Chrome doesn't seems to response to it anymore. I'll get deeper into this issue..

**Comment by Wouter0100** [comment]
This plugin became unneeded by the last Chrome update. Chrome implemented a multi-language spellchecker :+1:.

**Comment by 304NotModified** [comment]
Thanks for the info!
